/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 dummysat.glb
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props: any) {
//   const { nodes }: { nodes: any } = useGLTF('/dummysat.glb')
//   return (
//     <group {...props} rotation={props.rotation} dispose={null}>
//       <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} scale={[1, 2, 1]} />
//       <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0, 1.079, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.478, 1.921, 0.478]} />
//       <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[0, -0.105, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.392, 1.577, 0.392]} />
//       <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[0, -1.247, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 1.206, 0.3]} />
//       <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[0, 1.079, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.478, 1.921, 0.478]} />
//       <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[0, -0.105, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.392, 1.577, 0.392]} />
//       <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[0, -1.247, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.3, 1.206, 0.3]} />
//     </group>
//   )
// }

// useGLTF.preload('./dummysat.glb')
