/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dummysat.glb --transform
Files: dummysat.glb [56.78KB] > /home/ankush/Developer/CANSAT/ground-control-system/public/dummysat-transformed.glb [3.28KB] (94%)
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props: any) {
//   const { nodes, materials }: { nodes: any, materials: any } = useGLTF('/cansat.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} scale={[1, 2, 1]} />
//       <instancedMesh args={[nodes.Cylinder001.geometry, nodes.Cylinder001.material, 6]} instanceMatrix={nodes.Cylinder001.instanceMatrix} />
//     </group>
//   )
// }

// useGLTF.preload('/cansat.glb')
